
repos:
  - repo: local
    hooks:
      - id: mix-format
        name: mix format
        entry: bash -c 'mix format || true'
        language: system
        files: \.(ex|exs)'$
        types: [file, elixir]
        stages: [pre-commit]
        # This ensures that only staged files are formatted
        # and that the changes are re-added to the staging area.
        always_run: true
        pass_filenames: false
        require_serial: true
        description: "Runs mix format on staged Elixir files."
      - id: mix-credo
        name: mix credo
        entry: mix credo --strict
        language: system
        files: \.(ex|exs)'$
        types: [file, elixir]
        stages: [pre-commit]
        always_run: true
        pass_filenames: false
        require_serial: true
        description: "Runs mix credo --strict on staged Elixir files."
