
repos:
  - repo: local
    hooks:
      - id: mix-format
        name: mix format
        entry: mix format
        language: system
        files: \.(ex|exs)'$
        types: [file, elixir]
        stages: [pre-commit]
        # This ensures that only staged files are formatted
        # and that the changes are re-added to the staging area.
        always_run: true
        pass_filenames: false
        require_serial: true
        description: "Runs mix format on staged Elixir files."
