import Config

# Configure your database
config :blog, Blog.Repo,
  adapter: Ecto.Adapters.SQLite3,
  database: "priv/repo/blog_dev.db",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :blog, BlogWeb.Endpoint,
  # HTTP configuration for public access
  http: [ip: {127, 0, 0, 1}, port: 4000],
  # HTTPS with mTLS for API endpoints (development)
  https: [
    ip: {127, 0, 0, 1},
    port: 4001,
    cipher_suite: :strong,
    keyfile: "priv/cert/server/server-key.pem",
    certfile: "priv/cert/server/server-cert.pem",
    cacertfile: "priv/cert/ca/ca.pem",
    verify: :verify_peer,
    fail_if_no_peer_cert: false,  # Allow browser connections without client certs
    reuse_sessions: false,
    depth: 2
  ],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "P/MFuBor2fxglD+cZfVAdcKv1GNztGeFYflzyBilN/SMtGFnaFfJZRWCIzSjVXup",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:blog, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:blog, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :blog, BlogWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/blog_web/(controllers|live|components)/.*(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard
config :blog, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include HEEx debug annotations as HTML comments in rendered markup
  debug_heex_annotations: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Email configuration removed - not needed for this blog application

# Guardian development configuration

