name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: blog_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.17.2'
          otp-version: '27.0'

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            _build
            deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-

      - name: Install dependencies
        run: mix deps.get

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: assets/package-lock.json

      - name: Install Node.js dependencies
        run: npm install --prefix assets

      - name: Compile project
        run: mix compile --warnings-as-errors

      - name: Run tests
        run: mix test
        env:
          DATABASE_USER: postgres
          DATABASE_PASSWORD: postgres
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/blog_test

      - name: Check formatting
        run: mix format --check-formatted

      - name: Run Credo (informational)
        run: mix credo || true

  deploy:
    name: Build and Deploy Release
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Elixir for release
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.16.3'  # Match Gigalixir version
          otp-version: '26.2.5'     # Match Gigalixir version

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            _build
            deps
          key: ${{ runner.os }}-mix-release-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-release-

      - name: Install dependencies
        run: |
          mix local.hex --force
          mix local.rebar --force
          mix deps.get --only prod

      - name: Set up Node.js for asset compilation
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: assets/package-lock.json

      - name: Install Node.js dependencies
        run: npm install --prefix assets

      - name: Compile assets
        run: MIX_ENV=prod mix assets.deploy

      - name: Build release
        run: MIX_ENV=prod mix release
        env:
          SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}

      - name: Install Gigalixir CLI
        run: pip3 install gigalixir

      - name: Login to Gigalixir
        run: gigalixir login -e ${{ secrets.GIGALIXIR_USERNAME }} -y -p ${{ secrets.GIGALIXIR_PASSWORD }}

      - name: Deploy release to Gigalixir
        run: |
          gigalixir releases:upload _build/prod/blog-0.1.0.tar.gz --app_name ${{ secrets.GIGALIXIR_APP_NAME }}

      - name: Run migrations
        run: |
          gigalixir run --app_name ${{ secrets.GIGALIXIR_APP_NAME }} "bin/migrate"