name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: blog_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.17.2'
          otp-version: '27.0'

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            _build
            deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-

      - name: Install dependencies
        run: mix deps.get

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: assets/package-lock.json

      - name: Install Node.js dependencies
        run: npm install --prefix assets

      - name: Compile project
        run: mix compile --warnings-as-errors

      - name: Run tests
        run: mix test
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/blog_test

      - name: Check formatting
        run: mix format --check-formatted

      - name: Run Credo
        run: mix credo --strict

  deploy:
    name: Deploy to Gigalixir
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Gigalixir CLI
        run: |
          curl -fsSL https://github.com/gigalixir/gigalixir-cli/releases/download/v1.4.0/gigalixir_linux -o gigalixir
          chmod +x gigalixir
          sudo mv gigalixir /usr/local/bin/

      - name: Deploy to Gigalixir
        run: |
          echo "$GIGALIXIR_EMAIL" | gigalixir login
          gigalixir git:remote $GIGALIXIR_APP_NAME
          git push gigalixir HEAD:main
        env:
          GIGALIXIR_EMAIL: ${{ secrets.GIGALIXIR_EMAIL }}
          GIGALIXIR_PASSWORD: ${{ secrets.GIGALIXIR_PASSWORD }}
          GIGALIXIR_APP_NAME: ${{ secrets.GIGALIXIR_APP_NAME }}